<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5YWz5LqO');
$cfg_Cs[20]=array(17,1,1,'5peg57q/RFRV');
$cfg_Cs[19]=array(17,1,1,'5bel5Lia6Lev55Sx5Zmo');
$cfg_Cs[10]=array(0,1,1,'5qGI5L6L');
$cfg_Cs[12]=array(0,1,1,'5paw6Ze7');
$cfg_Cs[13]=array(0,1,1,'6IGU57O7');
$cfg_Cs[14]=array(0,1,1,'6aaW6aG15bm754Gv');
$cfg_Cs[15]=array(0,1,1,'5ZCI5L2c');
$cfg_Cs[24]=array(17,1,1,'566h55CG5bmz5Y+w');
$cfg_Cs[23]=array(17,1,1,'UE9F5Lqk5o2i5py6');
$cfg_Cs[22]=array(17,1,1,'5peg57q/5o6i6ZKI');
$cfg_Cs[21]=array(17,1,1,'6L2m6L295peg57q/57uI56uv');
$cfg_Cs[17]=array(0,1,1,'5Lqn5ZOB');
$cfg_Cs[16]=array(0,1,1,'5byA5Y+R5Zui6Zif');
?>